ALTER TABLE client ADD access_role VARCHAR(255) NOT NULL DEFAULT 'SYNC_API_ACCESS';

CREATE TABLE cpr_password_mapping (
   id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
   cpr VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL
);