package https.wsieksport_unilogin_dk.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2022-09-26T13:01:48.448+02:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "WsiEksport",
                  wsdlLocation = "https://wsieksport.unilogin.dk/wsieksport-v6/ws?WSDL",
                  targetNamespace = "https://wsieksport.unilogin.dk/ws")
public class WsiEksport extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://wsieksport.unilogin.dk/ws", "WsiEksport");
    public final static QName WsiEksportPort = new QName("https://wsieksport.unilogin.dk/ws", "WsiEksportPort");
    static {
        URL url = null;
        try {
            url = new URL("https://wsieksport.unilogin.dk/wsieksport-v6/ws?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsiEksport.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://wsieksport.unilogin.dk/wsieksport-v6/ws?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WsiEksport(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsiEksport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsiEksport() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsiEksport(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsiEksport(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsiEksport(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsiEksportPortType
     */
    @WebEndpoint(name = "WsiEksportPort")
    public WsiEksportPortType getWsiEksportPort() {
        return super.getPort(WsiEksportPort, WsiEksportPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsiEksportPortType
     */
    @WebEndpoint(name = "WsiEksportPort")
    public WsiEksportPortType getWsiEksportPort(WebServiceFeature... features) {
        return super.getPort(WsiEksportPort, WsiEksportPortType.class, features);
    }

}
