
package dk.stil.brugerdatabasen.bpi.wsieksport._7;

import jakarta.annotation.Generated;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-04-10T13:55:56.634+02:00
 * Generated source version: 4.1.4
 */

@WebFault(name = "authentificationError", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00", comments = "Apache CXF 4.1.4")
public class AuthentificationFault extends Exception {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00")
    private dk.stil.brugerdatabasen.common.v3.AuthentificationError faultInfo;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00")
    public AuthentificationFault() {
        super();
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00")
    public AuthentificationFault(String message) {
        super(message);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00")
    public AuthentificationFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00")
    public AuthentificationFault(String message, dk.stil.brugerdatabasen.common.v3.AuthentificationError authentificationError) {
        super(message);
        this.faultInfo = authentificationError;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00")
    public AuthentificationFault(String message, dk.stil.brugerdatabasen.common.v3.AuthentificationError authentificationError, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = authentificationError;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.634+02:00")
    public dk.stil.brugerdatabasen.common.v3.AuthentificationError getFaultInfo() {
        return this.faultInfo;
    }
}
