package dk.stil.brugerdatabasen.bpi.wsieksport._7;

import jakarta.annotation.Generated;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-04-10T13:55:56.678+02:00
 * Generated source version: 4.1.4
 *
 */
@WebService(targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", name = "WsiEksportPortType")
@XmlSeeAlso({ObjectFactory.class, dk.stil.brugerdatabasen.bpi.wsieksport._7.common.ObjectFactory.class, dk.stil.brugerdatabasen.bpi.wsieksport._7.fullmyndighed.ObjectFactory.class, dk.stil.brugerdatabasen.bpi.wsieksport._7.full.ObjectFactory.class, dk.stil.brugerdatabasen.bpi.wsieksport._7.medium.ObjectFactory.class, dk.stil.brugerdatabasen.common.v3.ObjectFactory.class, dk.stil.brugerdatabasen.bpi.wsieksport._7.small.ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00", comments = "Apache CXF 4.1.4")
public interface WsiEksportPortType {

    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/eksporterXmlFuldMyndighed")
    @RequestWrapper(localName = "eksporterXmlFuldMyndighed", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlRequestFuld")
    @ResponseWrapper(localName = "eksporterXmlFuldMyndighedResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseFullMyndighed")
    @WebResult(name = "xml", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseFullMyndighed.Xml eksporterXmlFuldMyndighed(

        @WebParam(name = "instnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        java.lang.String instnr,
        @WebParam(name = "filtre", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        dk.stil.brugerdatabasen.bpi.wsieksport._7.FiltreFuld filtre,
        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    /**
     * Returnerer en liste af institutionsnumre, hvor der er lavet en dataaftale til lille eksport
     */
    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/hentDataAftalerLille")
    @RequestWrapper(localName = "hentDataAftalerLille", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.NoArgs")
    @ResponseWrapper(localName = "hentDataAftalerLilleResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.HentDataAftalerResponse")
    @WebResult(name = "regnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public java.util.List<java.lang.String> hentDataAftalerLille(

        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    /**
     * Returnerer en liste af institutionsnumre, hvor der er lavet en dataaftale til fuld eksport
     */
    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/hentDataAftalerFuldMyndighed")
    @RequestWrapper(localName = "hentDataAftalerFuldMyndighed", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.NoArgs")
    @ResponseWrapper(localName = "hentDataAftalerFuldMyndighedResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.HentDataAftalerResponse")
    @WebResult(name = "regnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public java.util.List<java.lang.String> hentDataAftalerFuldMyndighed(

        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    /**
     * Ping webservicen med simpelt kald. Returnerer "Hello <udbydersystemID>!" hvis webservicen svarer, udbydersystemId er korrekt angivet og request er korrekt signeret med certifikat.
     */
    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/helloWorldWithCertificate")
    @RequestWrapper(localName = "helloWorldWithCertificate", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", className = "dk.stil.brugerdatabasen.common.v3.NoArgs")
    @ResponseWrapper(localName = "helloWorldWithCertificateResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", className = "dk.stil.brugerdatabasen.common.v3.HelloWorldResponse")
    @WebResult(name = "helloWorldResult", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public java.lang.String helloWorldWithCertificate(

        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/eksporterXmlMellem")
    @RequestWrapper(localName = "eksporterXmlMellem", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlRequestMellem")
    @ResponseWrapper(localName = "eksporterXmlMellemResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseMedium")
    @WebResult(name = "xml", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseMedium.Xml eksporterXmlMellem(

        @WebParam(name = "instnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        java.lang.String instnr,
        @WebParam(name = "filtre", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        dk.stil.brugerdatabasen.bpi.wsieksport._7.FiltreMellem filtre,
        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/eksporterXmlFuld")
    @RequestWrapper(localName = "eksporterXmlFuld", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlRequestFuld")
    @ResponseWrapper(localName = "eksporterXmlFuldResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseFull")
    @WebResult(name = "xml", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseFull.Xml eksporterXmlFuld(

        @WebParam(name = "instnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        java.lang.String instnr,
        @WebParam(name = "filtre", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        dk.stil.brugerdatabasen.bpi.wsieksport._7.FiltreFuld filtre,
        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    /**
     * Returnerer en liste af institutionsnumre, hvor der er lavet en dataaftale til fuld eksport
     */
    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/hentDataAftalerFuld")
    @RequestWrapper(localName = "hentDataAftalerFuld", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.NoArgs")
    @ResponseWrapper(localName = "hentDataAftalerFuldResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.HentDataAftalerResponse")
    @WebResult(name = "regnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public java.util.List<java.lang.String> hentDataAftalerFuld(

        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    /**
     * Returnerer en liste af institutionsnumre, hvor der er lavet en dataaftale til mellem eksport
     */
    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/hentDataAftalerMellem")
    @RequestWrapper(localName = "hentDataAftalerMellem", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.NoArgs")
    @ResponseWrapper(localName = "hentDataAftalerMellemResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.common.v3.HentDataAftalerResponse")
    @WebResult(name = "regnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public java.util.List<java.lang.String> hentDataAftalerMellem(

        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;

    @WebMethod(action = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7/eksporterXmlLille")
    @RequestWrapper(localName = "eksporterXmlLille", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlRequestSmall")
    @ResponseWrapper(localName = "eksporterXmlLilleResponse", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7", className = "dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseSmall")
    @WebResult(name = "xml", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.678+02:00")
    public dk.stil.brugerdatabasen.bpi.wsieksport._7.EksporterXmlResponseSmall.Xml eksporterXmlLille(

        @WebParam(name = "instnr", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        java.lang.String instnr,
        @WebParam(name = "filtre", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
        dk.stil.brugerdatabasen.bpi.wsieksport._7.FiltreLille filtre,
        @WebParam(name = "UdbydersystemId", targetNamespace = "https://brugerdatabasen.stil.dk/bpi/common/3", header = true)
        dk.stil.brugerdatabasen.common.v3.UdbydersystemIdType udbydersystemId
    ) throws AuthentificationFault;
}
