package dk.stil.brugerdatabasen.bpi.wsieksport._7;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import jakarta.annotation.Generated;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.4
 * 2026-04-10T13:55:56.693+02:00
 * Generated source version: 4.1.4
 *
 */
@WebServiceClient(name = "WsiEksport",
                  wsdlLocation = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7?wsdl",
                  targetNamespace = "https://brugerdatabasen.stil.dk/bpi/wsieksport/7")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00", comments = "Apache CXF 4.1.4")
public class WsiEksport extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public static final URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public static final QName SERVICE = new QName("https://brugerdatabasen.stil.dk/bpi/wsieksport/7", "WsiEksport");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public static final QName WsiEksportPort = new QName("https://brugerdatabasen.stil.dk/bpi/wsieksport/7", "WsiEksportPort");
    static {
        URL url = null;
        try {
            url = URI.create("https://brugerdatabasen.stil.dk/bpi/wsieksport/7?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsiEksport.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://brugerdatabasen.stil.dk/bpi/wsieksport/7?wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksport(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksport() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksport(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksport(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksport(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsiEksportPortType
     */
    @WebEndpoint(name = "WsiEksportPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksportPortType getWsiEksportPort() {
        return super.getPort(WsiEksportPort, WsiEksportPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsiEksportPortType
     */
    @WebEndpoint(name = "WsiEksportPort")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2026-04-10T13:55:56.693+02:00")
    public WsiEksportPortType getWsiEksportPort(WebServiceFeature... features) {
        return super.getPort(WsiEksportPort, WsiEksportPortType.class, features);
    }

}
