package dk.digitalidentity.service.model.enums;

public enum SetFieldType
{
	GROUP_AZURE_SECURITY_GROUP_ID,
	INSTITUTION_ALL_AZURE_SECURITY_GROUP_ID,
	INSTITUTION_STUDENT_AZURE_SECURITY_GROUP_ID,
	INSTITUTION_EMPLOYEE_AZURE_SECURITY_GROUP_ID;
}
